# Generated by Django 4.2.20 on 2025-05-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
