# Generated by Django 4.2.20 on 2025-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprises',
            options={},
        ),
    ]
