# Generated by Django 4.2.20 on 2025-05-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_enterprises_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='requisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='enterprises',
            table=None,
        ),
    ]
